services:
    phlexible_media_tool.imagine.imagick:
        class: Phlexible\Bundle\MediaToolBundle\Imagine\Imagick\Imagine

    phlexible_media_tool.imagine.gmagick:
        class: Imagine\Gmagick\Imagine

    phlexible_media_tool.imagine.gd:
        class: Imagine\Gd\Imagine

