services:
    phlexible_media_cache.instruction_processor:
        class: Phlexible\Component\MediaCache\Queue\InstructionProcessor
        arguments:
            - "@phlexible_media_cache.worker"
            - "@phlexible_media_type.media_type_manager"
            - "@logger"
        tags:
            - {name: monolog.logger, channel: media_cache}

    phlexible_media_cache.batch_processor:
        class: Phlexible\Component\MediaCache\Queue\BatchProcessor
        arguments:
            - "@phlexible_media_cache.instruction_creator"
            - "@phlexible_media_template.template_manager"
            - "@phlexible_media_manager.volume_manager"

    phlexible_media_cache.instruction_creator:
        class: Phlexible\Component\MediaCache\Queue\InstructionCreator
        arguments:
            - "@phlexible_media_cache.cache_manager"
            - "@phlexible_media_cache.id_strategy.default"
            - "@logger"
        tags:
            - {name: monolog.logger, channel: media_cache}
